[package]
name = "autoupdate"
version = "0.1.0"
edition = "2024"

[dependencies]
error = "0.1.9"
reqwest = { version = "0.12.26", features = ["json"] }
semver = "1.0.27"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }
